### ISSUE TITLE
Bug when you subscribe to new YouTube channel

### ISSUE THREAD

**Issue by JackConceprio1** [sudokid-software/filterme_issues#19]
When you have signed into filter app and subscribe to a new YouTube channel you will not see them in the list of subscribed channels and when I had fresh the did not update I have also tried signing in and out but that still did not work

**Comment by Sudo-Kid** [comment]
YouTube sub list not updating even after user reauths with Google.

**Comment by Sudo-Kid** [comment]
In 0.0.7
